import { waitForUser, getBackendAuthToken } from './firebase-state.js';
const BACKEND='https://patrimonio360-hqka.onrender.com';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const format=s=>esc(s).split('\n').map(x=>x?`<p>${x}</p>`:'').join('');
let history=[];
function message(role,text){const box=document.querySelector('#aiMessages');if(!box)return;const row=document.createElement('div');row.className=`ai-message ${role==='user'?'user':'assistant'}`;if(role==='assistant'){const a=document.createElement('div');a.className='ai-avatar';a.textContent='✦';row.appendChild(a);}const b=document.createElement('div');b.className='ai-bubble';b.innerHTML=role==='assistant'?format(text):`<p>${esc(text)}</p>`;row.appendChild(b);box.appendChild(row);box.scrollTop=box.scrollHeight;}
function ask(question){const clean=String(question||'').trim();if(!clean)return;message('user',clean);const box=document.querySelector('#aiMessages');const row=document.createElement('div');row.className='ai-message assistant';const a=document.createElement('div');a.className='ai-avatar';a.textContent='✦';const b=document.createElement('div');b.className='ai-bubble';b.innerHTML='<span class="ai-typing-label">Consultando o DeepSeek…</span>';row.append(a,b);box?.appendChild(row);box&&(box.scrollTop=box.scrollHeight);(async()=>{try{await waitForUser();const token=await getBackendAuthToken();const r=await fetch(`${BACKEND}/api/ai/chat`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({message:clean,selectedMonth:document.querySelector('#monthSelect')?.value||new Date().toISOString().slice(0,7),recent:history.slice(-20)})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'DeepSeek indisponível.');if(data.localAI===true)throw new Error('O backend informou uso de IA local.');b.innerHTML=format(data.answer||'Sem resposta do DeepSeek.');history.push({role:'user',content:clean},{role:'assistant',content:data.answer||''});history=history.slice(-20);}catch(e){b.innerHTML=`<p><strong>DeepSeek indisponível.</strong></p><p>${esc(e.message||'Não foi possível consultar o DeepSeek.')}</p><p>Nenhuma IA local será usada como fallback.</p>`;console.warn(e);}})();}
function intercept(e){const form=e.target?.closest?.('#aiForm');if(form){e.preventDefault();e.stopImmediatePropagation();const input=form.querySelector('#aiInput');const value=input?.value||'';if(input)input.value='';ask(value);return;}const s=e.target?.closest?.('.ai-suggestion');if(s){e.preventDefault();e.stopImmediatePropagation();ask(s.dataset.prompt);return;}const report=e.target?.closest?.('#aiReport');if(report){e.preventDefault();e.stopImmediatePropagation();ask('Faça um diagnóstico financeiro completo do meu mês, de forma simples e prática.');return;}const why=e.target?.closest?.('#aiWhy');if(why){e.preventDefault();e.stopImmediatePropagation();ask('Explique por que essas orientações são recomendadas com base nos meus dados financeiros atuais.');}}
document.addEventListener('submit',intercept,true);document.addEventListener('click',intercept,true);window.P360DeepSeekOnly={ask};
