// P360 Brazilian Financial Dataset v1
// Official sources are fetched at training time; raw datasets are not committed.
// BCB: 2023 Pesquisa de Letramento Financeiro (anonymized CSV).
// IBGE: POF/SIDRA table 751 (income classes / number of families).
const BCB_CATALOG='https://dadosabertos.bcb.gov.br/api/3/action/package_show?id=pesquisa-de-letramento-financeiro';
const IBGE_SIDRA='https://apisidra.ibge.gov.br/values/t/751/n1/1';
async function get(url){const r=await fetch(url,{headers:{'User-Agent':'Patrimonio360-Training/1.0'}});if(!r.ok)throw new Error(`HTTP ${r.status}: ${url}`);return r;}
function csv(s){const out=[];let row=[],c='',q=false;for(let i=0;i<s.length;i++){const x=s[i],n=s[i+1];if(x==='"'&&q&&n==='"'){c+='"';i++;continue}if(x==='"'){q=!q;continue}if(x===','&&!q){row.push(c);c='';continue}if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&n==='\n')i++;row.push(c);c='';if(row.some(v=>v.trim()))out.push(row);row=[];continue}c+=x}if(c||row.length){row.push(c);out.push(row)}const h=out.shift().map(x=>x.trim());return out.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()])))}
const n=v=>{const x=Number(String(v??'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''));return Number.isFinite(x)?x:null};
export async function fetchOfficialSources(){const catalog=await (await get(BCB_CATALOG)).json();const csvResource=(catalog.result?.resources||[]).find(x=>String(x.format).toLowerCase()==='csv');if(!csvResource?.url)throw new Error('BCB official CSV not found');const bcbRows=csv(await (await get(csvResource.url)).text());const ibgeRows=await (await get(IBGE_SIDRA)).json();return {bcbRows,ibgeRows,sources:[{organization:'Banco Central do Brasil',dataset:'Pesquisa de Letramento Financeiro',collection:'2023',url:csvResource.url},{organization:'IBGE',dataset:'POF/SIDRA table 751',period:'2017-2018',url:IBGE_SIDRA}]};}
function ibgeIncomeDistribution(rows){return rows.slice(1).map(r=>({class:r[2]||r[1],value:n(r[3]),unit:r[4]||'',period:r[0]||''})).filter(x=>x.value!==null);}
function bcbBehaviorSignals(rows){return rows.map((r,i)=>{const vals=Object.values(r).map(n).filter(v=>v!==null);return {id:i,numericFields:vals.length,positiveShare:vals.length?vals.filter(v=>v>0).length/vals.length:0}}).filter(x=>x.numericFields>=4);}
export async function buildBrazilTrainingSource(){const {bcbRows,ibgeRows,sources}=await fetchOfficialSources();return {metadata:{version:'br-v1',createdAt:new Date().toISOString(),sources,license:'BCB ODbL; IBGE public statistics',note:'Raw BCB survey observations are anonymized. Supervised labels must be mapped with the official BCB data dictionary before production training.'},income:ibgeIncomeDistribution(ibgeRows),behavior:bcbBehaviorSignals(bcbRows)};}
export async function saveBrazilTrainingSource(file='data/brazil-official-source.json'){const fs=await import('node:fs/promises');const path=await import('node:path');const d=await buildBrazilTrainingSource();await fs.mkdir(path.dirname(path.resolve(file)),{recursive:true});await fs.writeFile(path.resolve(file),JSON.stringify(d));return d;}
