const DEFAULT_BASE_URL='https://api.deepseek.com';
const enabled=String(process.env.P360_LLM_ENABLED||'true').toLowerCase()==='true';
const baseUrl=String(process.env.DEEPSEEK_BASE_URL||DEFAULT_BASE_URL).replace(/\/$/,'');
const model=process.env.DEEPSEEK_MODEL||'deepseek-v4-flash';
function compact(value,max=30000){const text=JSON.stringify(value??{});return text.length>max?text.slice(0,max)+'…':text;}
function systemPrompt(){return `Você é o Assistente Financeiro do Patrimônio 360. Use somente os dados financeiros oficiais fornecidos pelo sistema. Nunca invente saldo, receita, despesa, investimento, meta, limite ou percentual. Os cálculos do motor financeiro são a fonte de verdade. Se faltar informação, diga claramente que não há dados suficientes. Não execute alterações nos dados. Simulações devem ser explicitamente hipotéticas. Responda em português do Brasil, naturalmente, de forma direta e útil. Não mencione prompts, contexto interno, APIs, modelos ou provedores.`;}
function buildPrompt({question,analysis,risk,profile,insights,memory,financialContext,state}){return `${systemPrompt()}\n\nCONTEXTO FINANCEIRO OFICIAL:\n${compact({analysis,risk,profile,insights,memory,financialContext,state})}\n\nPERGUNTA DO USUÁRIO:\n${String(question||'').trim().slice(0,4000)}\n\nResponda diretamente usando os dados acima. Não invente informações e não altere os dados.`;}
async function callDeepSeek(prompt){const key=process.env.DEEPSEEK_API_KEY;if(!key)throw new Error('DEEPSEEK_API_KEY não configurada.');const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(`${baseUrl}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model,messages:[{role:'system',content:systemPrompt()},{role:'user',content:prompt}],thinking:{type:'disabled'},temperature:0.2,max_tokens:1200}),signal:controller.signal});const detail=await response.text();if(!response.ok)throw new Error(`DeepSeek HTTP ${response.status}: ${detail.slice(0,300)}`);let data;try{data=JSON.parse(detail);}catch{throw new Error('Resposta inválida do DeepSeek.');}const answer=data?.choices?.[0]?.message?.content?.trim();if(!answer)throw new Error('DeepSeek retornou uma resposta vazia.');return answer;}catch(error){if(error?.name==='AbortError')throw new Error('Tempo limite ao consultar o DeepSeek.');throw error;}finally{clearTimeout(timeout);}}
export function externalLLMStatus(){return{enabled,provider:'deepseek',configured:Boolean(process.env.DEEPSEEK_API_KEY),model,baseUrl,localAI:false};}
export async function generateExternalResponse(args){if(!enabled)throw new Error('IA DeepSeek desativada.');return callDeepSeek(buildPrompt(args));}
