import { detectIntent } from './intent-engine.js';
import { parseFinancialValue, parseGoal } from './value-parser.js';
import { buildFinancialContext, historicalContext, resolveRequestedMonth, transactionsForMonth } from './context-engine.js';
import { evaluatePurchase, explainPurchase } from './decision-engine.js';
import { completeDiagnosis } from './diagnosis-engine.js';
import { extractMemoryFromMessage } from '../memory/financial-memory.js';
import { scoreFinancialContext } from '../ml/financial-model.js';
import { reasonFinancially } from './natural-financial-engine.js';
import { generateNaturalResponse, neuralIntent } from './neural-conversation-engine.js';
import { simulatePurchase, simulateIncomeChange, simulateExtraIncome, simulateContribution } from './simulation-engine.js';
import { buildDatasetContext } from './dataset-v2-knowledge.js';
const money=v=>Number.isFinite(Number(v))?Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'não disponível';
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function inferredIntent(question,memory={}){const q=norm(question);if(/quanto.*(guardar|poupar|aportar).*(meta|ate|dezembro|mes)|quanto.*preciso.*(guardar|poupar|aportar)/.test(q))return 'goal';if(/^(e|entao)\b.*(guardar|poupar)|guardar.*(esse|isso)|investir.*esse/.test(q))return 'save_vs_invest';return null;}
function explicitTaskIntent(question){const q=norm(question);if(/analise.*cart|meus cartoes|minhas faturas|limite.*cartao|cartao.*credito|cartoes.*credito|cartao.*fatura|qual cartao.*pesando|usando muito.*cartao/.test(q))return 'cards';if(/o que tenho para pagar|o que tenho para receber|a pagar|a receber|vencimento|proximos dias|proximo mes|compromiss|o que vence primeiro|quanto tenho para pagar|quanto tenho para receber|dinheiro suficiente.*proxim/.test(q))return 'cashflow';if(/como posso melhorar.*orcamento|melhorar.*orcamento|organizar.*orcamento/.test(q))return 'budget';if(/onde gasto|meus gastos|minhas despesas|analis.*despesas|analis.*gastos|cortar gastos|onde consigo economizar|onde eu consigo economizar|estou gastando mais do que deveria/.test(q))return 'expenses';if(/quanto ainda posso gastar|quanto posso gastar/.test(q))return 'budget';if(/quanto tenho.*(banco|conta)|saldo.*(conta|banco)|dinheiro disponivel/.test(q))return 'accounts';return null;}
function recentUserMessages(memory={}){return (memory.recent||[]).filter(x=>x.role==='user').slice(-10);}
function recentPurchaseContext(memory={}){for(const item of [...recentUserMessages(memory)].reverse()){const text=norm(item.content||'');if(/comprar|compra|parcelar|parcelado|parcela|celular|tv|notebook|produto|eletronico/.test(text))return item.content||'';}return '';}
function recentPurchaseValue(memory={}){for(const item of [...recentUserMessages(memory)].reverse()){const parsed=parseFinancialValue(item.content||'');if(parsed.total>0)return {text:item.content||'',parsed};}return null;}
function purchaseQuestion(question,memory={}){const q=norm(question),parsed=parseFinancialValue(question),previousPurchase=recentPurchaseContext(memory),previousValue=recentPurchaseValue(memory);const continuation=/^(e|entao|mas|se|e se|quanto|qual|como|isso|esse|essa|ele|ela|nesse caso|em)\b|^\d+\s*x\b|^em\s+\d+\s*(?:x|vezes|parcelas?)/.test(q);if(!continuation)return question;const prior=previousValue?.parsed;if(prior?.total>0&&parsed.installments>1&&(parsed.total===0||parsed.total===parsed.installments))return `${previousValue.text} em ${parsed.installments}x`;if(prior?.total>0&&/^(em\s+)?\d+\s*(?:x|vezes|parcelas?)\b/.test(q))return `${previousValue.text} em ${parsed.installments||prior.installments}x`;if(prior?.total>0&&/parcel|vezes|\bx\b/.test(q))return `${previousValue.text} em ${parsed.installments||prior.installments}x`;if(previousPurchase&&prior?.total>0&&parsed.total>0)return `${previousPurchase} ${question}`;return question;}
function goalFromRecentMemory(memory={}){for(const item of [...(memory.recent||[])].reverse().slice(0,12)){const p=parseGoal(item.content||'',new Date());if(p?.target)return {id:`memory-${p.target}-${p.deadline||''}`,name:`Meta de ${money(p.target)}`,current:0,target:p.target,date:p.deadline||'',priority:'Alta',source:'conversation'};}return null;}
function findGoal(state,memory,question=''){const goals=state.goals||[];const q=norm(question);const preferred=memory.preferences?.find(p=>p.key==='activeFinancialGoal')?.value;const preferredTarget=memory.preferences?.find(p=>p.key==='activeFinancialGoalTarget')?.value;const explicit=goals.find(g=>String(g.id)===String(preferred));if(explicit)return explicit;const mentioned=goals.find(g=>q.includes(norm(g.name)));if(mentioned)return mentioned;const targetMatch=preferredTarget?.match(/^([\d.,]+)\|?(.*)$/);if(targetMatch){const target=Number(targetMatch[1].replace(/\./g,'').replace(',','.'));const byTarget=goals.find(g=>Math.abs(Number(g.target||0)-target)<0.01);if(byTarget)return byTarget;}const lastMentioned=memory.context?.lastMentionedGoalId;const recent=goals.find(g=>String(g.id)===String(lastMentioned));if(recent)return recent;const remembered=goalFromRecentMemory(memory);if(remembered)return remembered;return [...goals].sort((a,b)=>{const ap=String(a.priority||'').toLowerCase()==='alta'?0:1,bp=String(b.priority||'').toLowerCase()==='alta'?0:1;if(ap!==bp)return ap-bp;return Number(b.updatedAt||b.createdAt||0)-Number(a.updatedAt||a.createdAt||0);})[0]||null;}
function monthlyGoalNeed(goal){const target=Number(goal?.target||0),current=Number(goal?.current||0),remaining=Math.max(0,target-current),deadline=String(goal?.date||goal?.deadline||'');if(!remaining)return {remaining:0,monthly:0,months:0};if(!/^\d{4}-\d{2}$/.test(deadline))return {remaining,monthly:null,months:null};const [y,m]=deadline.split('-').map(Number),now=new Date(),months=Math.max(1,(y-now.getFullYear())*12+(m-(now.getMonth()+1))+1);return {remaining,monthly:remaining/months,months};}
function sanitizeResponse(text){return String(text||'').replace(/\b(?:BCB|Banco Central|IBGE|SIDRA|dataset|registros comportamentais|pontos de distribuição)\b[^.]*\.?/gi,'').replace(/\s{2,}/g,' ').trim();}
function conversationalGreeting(question){const q=norm(question);if(/^bom dia/.test(q))return 'Bom dia! 😊 Como posso ajudar você hoje?';if(/^boa tarde/.test(q))return 'Boa tarde! 😊 Como posso ajudar você hoje?';if(/^boa noite/.test(q))return 'Boa noite! 😊 Como posso ajudar você hoje?';if(/^fala|^e ai/.test(q))return 'Fala! 😄 O que você precisa resolver hoje?';return 'Olá! Tudo bem? 😊 Como posso ajudar você hoje?';}
function capabilitiesAnswer(){return 'Posso ajudar a controlar receitas e despesas, analisar compras e parcelas, acompanhar metas e reserva, analisar seu fluxo de caixa, identificar riscos, fazer simulações e usar seu histórico financeiro para personalizar as recomendações.';}
function historicalExpenseAnswer(state,month,question){const tx=transactionsForMonth(state,month);const expenses=tx.filter(t=>t.type==='expense');if(!expenses.length)return `Não encontrei despesas cadastradas em ${month}. Não vou substituir esse período pelos dados de outro mês.`;const categoryMatch=norm(question).match(/(?:com|de|em)\s+([a-z0-9áàâãéêíóôõúç ]+?)(?:\s+em\s+|\s+no\s+|\s+na\s+|\s+de\s+20\d{2}|\?|$)/);let selected=expenses;if(categoryMatch){const needle=categoryMatch[1].trim();const filtered=expenses.filter(t=>norm(t.category||'').includes(needle));if(filtered.length)selected=filtered;else return `Não encontrei despesas de ${categoryMatch[1].trim()} em ${month}. Não vou usar outra categoria ou outro período para preencher essa informação.`;}const total=selected.reduce((s,t)=>s+Number(t.value||0),0);const label=categoryMatch?.[1]?.trim();return label?`Em ${month}, encontrei ${selected.length} despesa(s) de ${label}, totalizando **${money(total)}**.`:`Em ${month}, você teve ${selected.length} despesa(s), totalizando **${money(total)}**.`;}
function currentExpenseAnswer(state,month,question){const q=norm(question);if(!/quanto|qto|qnto|total|soma|gastei/.test(q))return null;const expenses=transactionsForMonth(state,month).filter(t=>t.type==='expense');if(!expenses.length)return `Não encontrei despesas cadastradas em ${month}. Se quiser, posso analisar outro período.`;const total=expenses.reduce((s,t)=>s+Number(t.value||0),0);return `Até agora, em ${month}, você gastou **${money(total)}** em ${expenses.length} despesa(s).`}
function purchaseClarification(question,memory={}){
 const q=norm(question);
 const previousUsers=recentUserMessages(memory);
 const previousPurchaseIndex=[...previousUsers].reverse().findIndex(item=>/comprar|compra|parcelar|parcelado|parcela|celular|tv|notebook|produto|eletronico/.test(norm(item.content||'')));
 const previousPurchase=previousPurchaseIndex>=0;
 const distance=previousPurchaseIndex>=0?previousPurchaseIndex:Infinity;
 const previousValue=recentPurchaseValue(memory);
 const installmentOnly=/^(em\s+)?\d+\s*(?:x|vezes|parcelas?)\b/.test(q);
 if(installmentOnly&&previousValue?.parsed.total>0&&distance<=2)return null;
 const directPurchase=/comprar|compra|celular|tv|notebook|produto|eletronico|parcelar|parcelado|parcela|vale a pena|posso comprar/.test(q);
 if(!directPurchase)return null;
 const parsed=parseFinancialValue(question);
 if(parsed.total>0)return null;
 return 'Claro! Qual é o valor da compra que você quer avaliar? Pode me passar à vista ou parcelado, por exemplo: “R$ 1.200 em 5x”.';
}
function simulationAnswer(question,analysis,goal){const q=norm(question),parsed=parseFinancialValue(question);if(/compr|celular|tv|notebook|produto|compra|parcel/.test(q)&&parsed.total>0){const sim=simulatePurchase({analysis,goal,purchase:parsed});return `**Simulação — sem alterar seus dados**\n\nCompra de **${money(sim.total)}** em **${sim.installments}x de ${money(sim.monthly)}**.\n\nSua margem passaria de **${money(sim.currentMargin)}** para **${money(sim.simulatedMargin)}** por mês.\n${sim.goal?`\nA meta **${sim.goal.name}** continuaria ativa. ${sim.goal.projectedMonthly!=null?`O aporte mensal necessário subiria de ${money(sim.goal.baselineMonthly)} para ${money(sim.projectedMonthly)}.`:`O impacto mensal estimado sobre a capacidade de aporte é de ${money(sim.goal.impact)}.`}`:''}\n\n**Premissas:** ${sim.assumptions.join(' ')}`;}if(/renda.*(cair|diminuir|reduzir|menos)|salario.*(cair|diminuir|reduzir|menos)/.test(q)&&parsed.total>0){const sim=simulateIncomeChange({analysis,delta:-parsed.total});return `**Simulação — renda ${money(sim.delta)} menor**\n\nRenda estimada: **${money(sim.simulatedIncome)}**.\nMargem estimada: **${money(sim.simulatedMargin)}** (antes: ${money(sim.currentMargin)}).\n\nNenhum dado real foi alterado.`;}if(/receber|extra|aumentar.*renda|renda.*aumentar/.test(q)&&parsed.total>0){const sim=simulateExtraIncome({analysis,amount:parsed.total});return `**Simulação — renda extra de ${money(sim.delta)}**\n\nRenda estimada: **${money(sim.simulatedIncome)}**.\nMargem estimada: **${money(sim.simulatedMargin)}**.\n\nNenhum dado real foi alterado.`;}if(/aporte|guardar|poupar|economizar|juntar/.test(q)&&parsed.total>0){const sim=simulateContribution({analysis,goal,amount:parsed.total});return `**Simulação de aporte de ${money(sim.amount)}**\n\nMargem após o aporte: **${money(sim.simulatedMargin)}**.\nReserva projetada: **${money(sim.reserveAfter)}**.\n${sim.goal?`\nMeta **${sim.goal.name}**: faltariam ${money(sim.goal.remainingAfter)}.`:''}\n\nNenhum dado real foi alterado.`;}return 'Consigo simular esse cenário, mas preciso de um valor ou mudança concreta. Exemplo: “E se eu comprar por R$ 1.200 em 5x?”';}
export async function respondV2({question,state,currentMonth,memory,analysis,risk,profile,insights}){
 const inferred=inferredIntent(question,memory);const explicit=explicitTaskIntent(question);const baseIntent=detectIntent(question,memory);const n=neuralIntent(question,memory);const clarification=purchaseClarification(question,memory);const deterministicIntent=clarification?'purchase':inferred||explicit||(baseIntent&&!['general','continuation'].includes(baseIntent)?baseIntent:null);const intent=deterministicIntent||((n.score>=0.8)?n.intent:baseIntent||'general');const month=resolveRequestedMonth(question,currentMonth);const context=buildFinancialContext(state,month,memory);context.analysis=analysis;context.risk=risk;context.budget=analysis?.budget||null;context.neuralIntent=n;context.dataset=buildDatasetContext(question);
 const financialModel=await scoreFinancialContext({analysis,goals:state.goals||[],reserve:analysis?.reserve?.current||0},{deviation:0});context.financialModel=financialModel;const memoryPatch=extractMemoryFromMessage(question);let answer=null,mutation=null,decision=null;let activeGoal=findGoal(state,memory,question);
 if(clarification)answer=clarification;
 else if(intent==='greeting')answer=conversationalGreeting(question);
 else if(intent==='capabilities')answer=capabilitiesAnswer();
 else if(intent==='historical_expenses')answer=historicalExpenseAnswer(state,month,question);
 else if(intent==='historical_income'){const h=historicalContext(state,month);answer=!h.found?`Não encontrei receitas cadastradas em ${month}. Não vou substituir esse período pelos dados de outro mês.`:`Em ${month}, encontrei ${money(h.income)} em receitas registradas. Desse valor, ${money(h.received)} já consta como recebido e ${money(h.income-h.received)} está pendente.`;}
 else if(intent==='simulation'){answer=simulationAnswer(question,analysis,activeGoal);context.simulation={readOnly:true};}
 else if(intent==='save_vs_invest'){const reserve=Number(analysis?.reserve?.current||0),income=Number(analysis?.income?.total||0),expense=Number(analysis?.expenses?.total||0),planned=Number.isFinite(Number(analysis?.cashflow?.planned))?Number(analysis.cashflow.planned):income-expense,g=monthlyGoalNeed(activeGoal),reserveWeak=income>0&&reserve<income*3,cashTight=planned<=0;decision={recommendation:cashTight||reserveWeak?'Eu priorizaria guardar agora. Você está com pouca folga ou uma reserva ainda em formação. Primeiro proteja a liquidez; depois, com a base mais forte, podemos direcionar o excedente para investimentos.':'Sua reserva já está mais protegida. Eu dividiria o excedente entre a meta de curto prazo e investimentos compatíveis com o prazo e seu risco.'};answer=generateNaturalResponse({question,decision,memory,goal:activeGoal,facts:{monthlyNeed:g.monthly}})||decision.recommendation;answer+=`\n\nHoje você tem ${money(reserve)} de reserva e o resultado planejado do período é ${money(planned)}.`;if(activeGoal)answer+=` Sua prioridade considerada é **${activeGoal.name}**, faltando ${money(g.remaining)}${g.monthly!=null?` (aprox. ${money(g.monthly)}/mês até ${activeGoal.date||activeGoal.deadline})`:''}.`;}
 else if(intent==='purchase'){const parsed=parseFinancialValue(question);if(!parsed.total){answer='Qual é o valor total da compra que você quer avaliar?';}else{const normalizedQuestion=purchaseQuestion(question,memory);decision=evaluatePurchase(normalizedQuestion,context,memory);answer=explainPurchase(decision);}}
 else if(intent==='goal'){const parsed=parseGoal(question,new Date());const reference=/(quanto|mes|m[eê]s|guardar|aportar|preciso|nessa meta|essa meta|meta)/.test(norm(question));const existing=parsed?.target?(state.goals||[]).find(g=>Math.abs(Number(g.target||0)-parsed.target)<.01&&(!parsed.deadline||String(g.date||g.deadline||'').startsWith(parsed.deadline))):null;if(parsed?.target){if(existing){answer=`Já existe uma meta oficial de ${money(parsed.target)} cadastrada. Vou usá-la como referência nas próximas análises.`;}else{const createdAt=new Date().toISOString();mutation={type:'createGoal',goal:{id:Date.now(),name:`Meta de ${money(parsed.target)}`,current:0,target:parsed.target,date:parsed.deadline||'',priority:'Alta',createdAt,updatedAt:createdAt}};memoryPatch.preferences=[...(memoryPatch.preferences||[]),{key:'activeFinancialGoal',label:'Meta financeira atual',value:String(mutation.goal.id),source:'conversation',updatedAt:createdAt},{key:'activeFinancialGoalTarget',label:'Meta financeira alvo',value:`${parsed.target}|${parsed.deadline||''}`,source:'conversation',updatedAt:createdAt}];answer=`Registrei a meta de ${money(parsed.target)}${parsed.deadline?` até ${parsed.deadline}`:''}. Ela passa a ser considerada nas análises de compras, aportes e fluxo.`;}}else if(reference){activeGoal=findGoal(state,memory,question);if(activeGoal){const g=monthlyGoalNeed(activeGoal);answer=`Sua meta registrada é **${activeGoal.name}**: ${money(activeGoal.current||0)} de ${money(activeGoal.target||0)}. Faltam **${money(g.remaining)}**${g.monthly!=null?` e, considerando o prazo de ${activeGoal.date||activeGoal.deadline}, você precisa guardar aproximadamente **${money(g.monthly)} por mês** durante ${g.months} mês(es).`:'.'}`;}else answer='Não encontrei uma meta oficial registrada. Informe o valor e o prazo para eu calcular o aporte necessário.';}else answer='Posso acompanhar a meta, mas preciso do valor-alvo. Exemplo: “Quero chegar a R$ 5.000 até dezembro”.';}
 else if(intent==='diagnosis'){const d=completeDiagnosis(context,analysis,profile,insights);answer=`**Diagnóstico financeiro**\n\nRisco: **${d.risk.level}** (${d.risk.score}/100). ${d.risk.explanation||''}\n\n**3 prioridades:**\n${d.topProblems.map((p,i)=>`${i+1}. **${p.title}** — ${p.reason}\n   Primeiro passo: ${p.action}`).join('\n')||'Não encontrei três problemas sustentados pelos dados atuais.'}`;}
 else if(intent==='cards'||intent==='cashflow'||intent==='budget'||intent==='expenses'||intent==='accounts'){if(intent==='expenses'){const direct=currentExpenseAnswer(state,month,question);if(direct)answer=direct;}if(!answer){const natural=await reasonFinancially({question,state,analysis,risk,profile,memory,goals:state.goals||[]});answer=natural.text;context.brazilBenchmark=natural.benchmark;}}
 else if(intent==='feedback'){const priorityMatch=question.match(/(?:minha prioridade (?:agora )?(?:é|e)|prioridade (?:agora )?(?:é|e))\s*(.+?)(?:[.!?]|$)/i);if(priorityMatch){memoryPatch.preferences=[...(memoryPatch.preferences||[]),{key:'activeFinancialPriority',label:'Prioridade financeira atual',value:priorityMatch[1].trim(),source:'conversation',updatedAt:new Date().toISOString()}];context.activeFinancialPriority=priorityMatch[1].trim();answer=`Entendi. Registrei **${priorityMatch[1].trim()}** como sua prioridade financeira atual. Nas próximas decisões, ela terá precedência sobre metas antigas, salvo se você mudar essa prioridade.`;}else answer='Entendi a correção. Vou registrá-la na memória estruturada para evitar repetir esse erro.';}
 else if(intent==='memory')answer=`Tenho ${(memory.facts||[]).length} fato(s), ${(memory.goals||[]).length} meta(s), ${(memory.preferences||[]).length} preferência(s) e ${(memory.corrections||[]).length} correção(ões) na memória. Os dados financeiros oficiais continuam vindo do banco.`;
 if(!answer){const natural=await reasonFinancially({question,state,analysis,risk,profile,memory,goals:state.goals||[]});answer=natural.text;context.brazilBenchmark=natural.benchmark;}
 return {answer:sanitizeResponse(answer),intent,month,context,memoryPatch,mutation,financialModel};
}
