import { detectIntent } from './intent-engine.js';
import { parseFinancialValue, parseGoal } from './value-parser.js';
import { buildFinancialContext, historicalContext, resolveRequestedMonth } from './context-engine.js';
import { evaluatePurchase, explainPurchase } from './decision-engine.js';
import { completeDiagnosis } from './diagnosis-engine.js';
import { extractMemoryFromMessage } from '../memory/financial-memory.js';
import { scoreFinancialContext } from '../ml/financial-model.js';
import { reasonFinancially } from './natural-financial-engine.js';
import { generateNaturalResponse, neuralIntent } from './neural-conversation-engine.js';
const money=v=>Number.isFinite(Number(v))?Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'não disponível';
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function purchaseQuestion(question,memory={}){const parsed=parseFinancialValue(question),q=norm(question);const continuation=/^(e|entao|mas|se|e se|quanto|qual|como|isso|nesse caso)\b|^\d+\s*x\b|^em\s+\d+\s*(?:x|vezes|parcelas?)/i.test(q);if(!continuation)return question;const previous=[...(memory.recent||[])].reverse().find(x=>x.role==='user'&&parseFinancialValue(x.content||'').total>0)?.content;if(!previous)return question;const prior=parseFinancialValue(previous);if(prior.total>0&&parsed.installments>1&&(parsed.total===0||parsed.total===parsed.installments))return `${previous} em ${parsed.installments}x`;if(prior.total>0&&/parcel|vezes|\bx\b/.test(q))return `${previous} em ${parsed.installments||prior.installments}x`;return question;}
function findGoal(state,memory,question=''){const goals=state.goals||[];if(!goals.length)return null;const q=norm(question);const preferred=memory.preferences?.find(p=>p.key==='activeFinancialGoal')?.value;const explicit=goals.find(g=>String(g.id)===String(preferred));if(explicit)return explicit;const mentioned=goals.find(g=>q.includes(norm(g.name)));if(mentioned)return mentioned;const lastMentioned=memory.context?.lastMentionedGoalId;const recent=goals.find(g=>String(g.id)===String(lastMentioned));if(recent)return recent;return [...goals].sort((a,b)=>{const ap=String(a.priority||'').toLowerCase()==='alta'?0:1,bp=String(b.priority||'').toLowerCase()==='alta'?0:1;if(ap!==bp)return ap-bp;return Number(b.updatedAt||b.createdAt||0)-Number(a.updatedAt||a.createdAt||0);})[0]||null;}
function monthlyGoalNeed(goal){const target=Number(goal?.target||0),current=Number(goal?.current||0),remaining=Math.max(0,target-current);const deadline=String(goal?.date||goal?.deadline||'');if(!remaining)return {remaining:0,monthly:0,months:0};if(!/^\d{4}-\d{2}$/.test(deadline))return {remaining,monthly:null,months:null};const [y,m]=deadline.split('-').map(Number),now=new Date(),months=Math.max(1,(y-now.getFullYear())*12+(m-(now.getMonth()+1))+1);return {remaining,monthly:remaining/months,months};}
export async function respondV2({question,state,currentMonth,memory,analysis,risk,profile,insights}){
 const baseIntent=detectIntent(question,memory),n=neuralIntent(question,memory),intent=n.score>=0.8?n.intent:baseIntent,month=resolveRequestedMonth(question,currentMonth),context=buildFinancialContext(state,month,memory);context.analysis=analysis;context.risk=risk;context.budget=analysis?.budget||null;context.neuralIntent=n;
 const financialModel=await scoreFinancialContext({analysis,goals:state.goals||[],reserve:analysis?.reserve?.current||0},{deviation:0});context.financialModel=financialModel;const memoryPatch=extractMemoryFromMessage(question);let answer=null,mutation=null,decision=null;let activeGoal=findGoal(state,memory,question);
 if(intent==='historical_income'){const h=historicalContext(state,month);answer=!h.found?`Não encontrei receitas cadastradas em ${month}. Não vou substituir esse período pelos dados de outro mês.`:`Em ${month}, encontrei ${money(h.income)} em receitas registradas. Desse valor, ${money(h.received)} já consta como recebido e ${money(h.income-h.received)} está pendente.`;}
 else if(intent==='save_vs_invest'){const reserve=Number(analysis?.reserve?.current||0),income=Number(analysis?.income?.total||0),expense=Number(analysis?.expenses?.total||0),planned=Number.isFinite(Number(analysis?.cashflow?.planned))?Number(analysis.cashflow.planned):income-expense,g=monthlyGoalNeed(activeGoal),reserveWeak=income>0&&reserve<income*3,cashTight=planned<=0;decision={recommendation:cashTight||reserveWeak?'Eu priorizaria guardar agora. Você está com pouca folga ou uma reserva ainda em formação. Primeiro proteja a liquidez; depois, com a base mais forte, podemos direcionar o excedente para investimentos.':'Sua reserva já está mais protegida. Eu dividiria o excedente entre a meta de curto prazo e investimentos compatíveis com o prazo e seu risco.'};answer=generateNaturalResponse({question,decision,memory,goal:activeGoal,facts:{monthlyNeed:g.monthly}})||decision.recommendation;answer+=`\n\nHoje você tem ${money(reserve)} de reserva e o resultado planejado do período é ${money(planned)}.`;if(activeGoal)answer+=` Sua prioridade considerada é **${activeGoal.name}**, faltando ${money(g.remaining)}${g.monthly!=null?` (aprox. ${money(g.monthly)}/mês até ${activeGoal.date||activeGoal.deadline})`:''}.`;}
 else if(intent==='purchase'){decision=evaluatePurchase(purchaseQuestion(question,memory),context,memory);answer=explainPurchase(decision);}
 else if(intent==='goal'){const parsed=parseGoal(question,new Date());const reference=/(quanto|mes|m[eê]s|guardar|aportar|preciso|nessa meta|essa meta|meta)/.test(norm(question));const existing=parsed?.target?(state.goals||[]).find(g=>Math.abs(Number(g.target||0)-parsed.target)<.01&&(!parsed.deadline||String(g.date||g.deadline||'').startsWith(parsed.deadline))):null;if(parsed?.target){if(existing)answer=`Já existe uma meta oficial de ${money(parsed.target)} cadastrada. Vou usá-la como referência nas próximas análises.`;else{const createdAt=new Date().toISOString();mutation={type:'createGoal',goal:{id:Date.now(),name:`Meta de ${money(parsed.target)}`,current:0,target:parsed.target,date:parsed.deadline||'',priority:'Alta',createdAt,updatedAt:createdAt}};memoryPatch.preferences=[...(memoryPatch.preferences||[]),{key:'activeFinancialGoal',label:'Meta financeira atual',value:String(mutation.goal.id),source:'conversation',updatedAt:createdAt}];answer=`Registrei a meta de ${money(parsed.target)}${parsed.deadline?` até ${parsed.deadline}`:''}. Ela passa a ser considerada nas análises de compras, aportes e fluxo.`;}}else if(reference){activeGoal=findGoal(state,memory,question);if(activeGoal){const g=monthlyGoalNeed(activeGoal);answer=`Sua meta registrada é **${activeGoal.name}**: ${money(activeGoal.current||0)} de ${money(activeGoal.target||0)}. Faltam **${money(g.remaining)}**${g.monthly!=null?` e, considerando o prazo de ${activeGoal.date||activeGoal.deadline}, você precisa guardar aproximadamente **${money(g.monthly)} por mês** durante ${g.months} mês(es).`:'.'}`;}else answer='Não encontrei uma meta oficial registrada. Informe o valor e o prazo para eu calcular o aporte necessário.';}else answer='Posso acompanhar a meta, mas preciso do valor-alvo. Exemplo: “Quero chegar a R$ 5.000 até dezembro”.';}
 else if(intent==='diagnosis'){const d=completeDiagnosis(context,analysis,profile,insights);answer=`**Diagnóstico financeiro**\n\nRisco: **${d.risk.level}** (${d.risk.score}/100). ${d.risk.explanation||''}\n\n**3 prioridades:**\n${d.topProblems.map((p,i)=>`${i+1}. **${p.title}** — ${p.reason}\n   Primeiro passo: ${p.action}`).join('\n')||'Não encontrei três problemas sustentados pelos dados atuais.'}`;}
 else if(intent==='feedback'){const priorityMatch=question.match(/(?:minha prioridade (?:agora )?(?:é|e)|prioridade (?:agora )?(?:é|e))\s*(.+?)(?:[.!?]|$)/i);if(priorityMatch){memoryPatch.preferences=[...(memoryPatch.preferences||[]),{key:'activeFinancialPriority',label:'Prioridade financeira atual',value:priorityMatch[1].trim(),source:'conversation',updatedAt:new Date().toISOString()}];context.activeFinancialPriority=priorityMatch[1].trim();answer=`Entendi. Registrei **${priorityMatch[1].trim()}** como sua prioridade financeira atual. Nas próximas decisões, ela terá precedência sobre metas antigas, salvo se você mudar essa prioridade.`;}else answer='Entendi a correção. Vou registrá-la na memória estruturada para evitar repetir esse erro.';}
 else if(intent==='memory')answer=`Tenho ${(memory.facts||[]).length} fato(s), ${(memory.goals||[]).length} meta(s), ${(memory.preferences||[]).length} preferência(s) e ${(memory.corrections||[]).length} correção(ões) na memória. Os dados financeiros oficiais continuam vindo do banco.`;
 if(!answer){const natural=await reasonFinancially({question,state,analysis,risk,profile,memory,goals:state.goals||[]});answer=natural.text;context.brazilBenchmark=natural.benchmark;}
 return {answer,intent,month,context,memoryPatch,mutation,financialModel};
}
